# 100 A1 Essential Words (Ranks 1-100)
# (key, pos, cefr, cat, de, ru, uk, es, fr, it, pt, zh, ja, ko)

def e(k, p, l, c, de, ru, uk, es, fr, it, pt, zh, ja, ko):
    return {
        "key": k, "pos": p, "cefr": l, "cat": c,
        "trans": {
            "de": de, "ru": ru, "uk": uk, "es": es, "fr": fr,
            "it": it, "pt": pt, "zh": zh, "ja": ja, "ko": ko, "en": k
        }
    }

A1_WORDS = [
    # Pronouns & Basics
    e("I", "pronoun", "A1", "Everyday Life", "ich", "я", "я", "yo", "je", "io", "eu", "我", "私", "나"),
    e("you", "pronoun", "A1", "Everyday Life", "du", "ты", "ти", "tú", "tu", "tu", "você", "你", "あなた", "너"),
    e("he", "pronoun", "A1", "Everyday Life", "er", "он", "він", "él", "il", "lui", "ele", "他", "彼", "그"),
    e("she", "pronoun", "A1", "Everyday Life", "sie", "она", "вона", "ella", "elle", "lei", "ela", "她", "彼女", "그녀"),
    e("we", "pronoun", "A1", "Everyday Life", "wir", "мы", "ми", "nosotros", "nous", "noi", "nós", "我们", "私たち", "우리"),
    e("they", "pronoun", "A1", "Everyday Life", "sie", "они", "вони", "ellos", "ils", "loro", "eles", "他们", "彼ら", "그들"),
    e("yes", "adverb", "A1", "Everyday Life", "ja", "да", "так", "sí", "oui", "sì", "sim", "是", "はい", "네"),
    e("no", "adverb", "A1", "Everyday Life", "nein", "нет", "ні", "no", "non", "no", "não", "不", "いいえ", "아니오"),
    e("please", "adverb", "A1", "Everyday Life", "bitte", "пожалуйста", "будь ласка", "por favor", "s'il vous plaît", "per favore", "por favor", "请", "お願いします", "부탁합니다"),
    e("thank you", "adverb", "A1", "Everyday Life", "danke", "спасибо", "дякую", "gracias", "merci", "grazie", "obrigado", "谢谢", "ありがとう", "감사합니다"),
    e("hello", "adverb", "A1", "Everyday Life", "hallo", "привет", "привіт", "hola", "bonjour", "ciao", "olá", "你好", "こんにちは", "안녕하세요"),
    e("goodbye", "adverb", "A1", "Everyday Life", "auf Wiedersehen", "до свидания", "до побачення", "adiós", "au revoir", "arrivederci", "adeus", "再见", "さようなら", "안녕히 가세요"),
    
    # Core Verbs
    e("to be", "verb", "A1", "Action Verbs", "sein", "быть", "бути", "ser", "être", "essere", "ser", "是", "である", "이다"),
    e("to have", "verb", "A1", "Action Verbs", "haben", "иметь", "мати", "tener", "avoir", "avere", "ter", "有", "持っている", "가지다"),
    e("to do", "verb", "A1", "Action Verbs", "machen", "делать", "робити", "hacer", "faire", "fare", "fazer", "做", "する", "하다"),
    e("to go", "verb", "A1", "Action Verbs", "gehen", "идти", "йти", "ir", "aller", "andare", "ir", "去", "行く", "가다"),
    e("to come", "verb", "A1", "Action Verbs", "kommen", "приходить", "приходити", "venir", "venir", "venire", "vir", "来", "来る", "오다"),
    e("to see", "verb", "A1", "Action Verbs", "sehen", "видеть", "бачити", "ver", "voir", "vedere", "ver", "看", "見る", "보다"),
    e("to hear", "verb", "A1", "Action Verbs", "hören", "слышать", "чути", "oír", "entendre", "sentire", "ouvir", "听", "聞く", "듣다"),
    e("to eat", "verb", "A1", "Action Verbs", "essen", "есть", "їсти", "comer", "manger", "mangiare", "comer", "吃", "食べる", "먹다"),
    e("to drink", "verb", "A1", "Action Verbs", "trinken", "пить", "пити", "beber", "boire", "bere", "beber", "喝", "飲む", "마시다"),
    e("to sleep", "verb", "A1", "Action Verbs", "schlafen", "спать", "спати", "dormir", "dormir", "dormire", "dormir", "睡觉", "眠る", "자다"),
    e("to speak", "verb", "A1", "Action Verbs", "sprechen", "говорить", "говорити", "hablar", "parler", "parlare", "falar", "说话", "話す", "말하다"),
    e("to read", "verb", "A1", "Action Verbs", "lesen", "читать", "читати", "leer", "lire", "leggere", "ler", "读", "読む", "읽다"),
    e("to write", "verb", "A1", "Action Verbs", "schreiben", "писать", "писати", "escribir", "écrire", "scrivere", "escrever", "写", "書く", "쓰다"),
    e("to buy", "verb", "A1", "Action Verbs", "kaufen", "покупать", "купувати", "comprar", "acheter", "comprare", "comprar", "买", "買う", "사다"),
    e("to understand", "verb", "A1", "Action Verbs", "verstehen", "понимать", "розуміти", "entender", "comprendre", "capire", "entender", "明白", "理解する", "이해하다"),
    e("to know", "verb", "A1", "Action Verbs", "wissen", "знать", "знати", "saber", "savoir", "sapere", "saber", "知道", "知る", "알다"),
    e("to want", "verb", "A1", "Action Verbs", "wollen", "хотеть", "хотіти", "querer", "vouloir", "volere", "querer", "想要", "欲しい", "원하다"),
    e("to live", "verb", "A1", "Action Verbs", "leben", "жить", "жити", "vivir", "vivre", "vivere", "viver", "生活", "生きる", "살다"),
    e("to work", "verb", "A1", "Action Verbs", "arbeiten", "работать", "працювати", "trabajar", "travailler", "lavorare", "trabalhar", "工作", "働く", "일하다"),
    e("to open", "verb", "A1", "Action Verbs", "öffnen", "открывать", "відкривати", "abrir", "ouvrir", "aprire", "abrir", "打开", "開ける", "열다"),
    e("to close", "verb", "A1", "Action Verbs", "schließen", "закрывать", "закривати", "cerrar", "fermer", "chiudere", "fechar", "关闭", "閉める", "닫다"),
    e("to give", "verb", "A1", "Action Verbs", "geben", "давать", "давати", "dar", "donner", "dare", "dar", "给", "与える", "주다"),
    e("to take", "verb", "A1", "Action Verbs", "nehmen", "брать", "брати", "tomar", "prendre", "prendere", "tomar", "拿", "取る", "받다"),
    e("to help", "verb", "A1", "Action Verbs", "helfen", "помогать", "допомагати", "ayudar", "aider", "aiutare", "ajudar", "帮助", "助ける", "돕다"),
    e("to learn", "verb", "A1", "Action Verbs", "lernen", "учить", "вчити", "aprender", "apprendre", "imparare", "aprender", "学习", "学ぶ", "배우다"),
    e("to play", "verb", "A1", "Action Verbs", "spielen", "играть", "грати", "jugar", "jouer", "giocare", "jogar", "玩", "遊ぶ", "놀다"),
    e("to wait", "verb", "A1", "Action Verbs", "warten", "ждать", "чекати", "esperar", "attendre", "aspettare", "esperar", "等待", "待つ", "기다리다"),
    e("to think", "verb", "A1", "Action Verbs", "denken", "думать", "думати", "pensar", "penser", "pensare", "pensar", "思考", "考える", "생각하다"),
    e("to find", "verb", "A1", "Action Verbs", "finden", "находить", "знаходити", "encontrar", "trouver", "trovare", "encontrar", "找到", "見つける", "찾다"),
    e("to call", "verb", "A1", "Action Verbs", "rufen", "звонить", "дзвонити", "llamar", "appeler", "chiamare", "chamar", "呼叫", "呼ぶ", "부르다"),
    e("to ask", "verb", "A1", "Action Verbs", "fragen", "спрашивать", "запитувати", "preguntar", "demander", "chiedere", "perguntar", "询问", "尋ねる", "묻다"),
    e("to answer", "verb", "A1", "Action Verbs", "antworten", "отвечать", "відповідати", "responder", "répondre", "rispondere", "responder", "回答", "答える", "대답하다"),
    e("to pay", "verb", "A1", "Action Verbs", "bezahlen", "платить", "платити", "pagar", "payer", "pagare", "pagar", "支付", "支払う", "지불하다"),
    e("to start", "verb", "A1", "Action Verbs", "beginnen", "начинать", "починати", "empezar", "commencer", "iniziare", "começar", "开始", "始める", "시작하다"),
    e("to finish", "verb", "A1", "Action Verbs", "beenden", "заканчивать", "закінчувати", "terminar", "finir", "finire", "terminar", "结束", "終える", "끝내다"),

    # Core Nouns
    e("person", "noun", "A1", "Society & Culture", "die Person", "человек", "людина", "la persona", "la personne", "la persona", "a pessoa", "人", "人", "사람"),
    e("man", "noun", "A1", "Society & Culture", "der Mann", "мужчина", "чоловік", "el hombre", "l'homme", "l'uomo", "o homem", "男人", "男性", "남자"),
    e("woman", "noun", "A1", "Society & Culture", "die Frau", "женщина", "жінка", "la mujer", "la femme", "la donna", "a mulher", "女人", "女性", "여자"),
    e("child", "noun", "A1", "Society & Culture", "das Kind", "ребёнок", "дитина", "el niño", "l'enfant", "il bambino", "a criança", "孩子", "子供", "아이"),
    e("friend", "noun", "A1", "Society & Culture", "der Freund", "друг", "друг", "el amigo", "l'ami", "l'amico", "o amigo", "朋友", "友達", "친구"),
    e("family", "noun", "A1", "Society & Culture", "die Familie", "семья", "сім'я", "la familia", "la famille", "la famiglia", "a família", "家庭", "家族", "가족"),
    e("house", "noun", "A1", "Everyday Life", "das Haus", "дом", "будинок", "la casa", "la maison", "la casa", "a casa", "房屋", "家", "집"),
    e("room", "noun", "A1", "Everyday Life", "das Zimmer", "комната", "кімната", "la habitación", "la chambre", "la stanza", "o quarto", "房间", "部屋", "방"),
    e("door", "noun", "A1", "Everyday Life", "die Tür", "дверь", "двері", "la puerta", "la porte", "la porta", "a porta", "门", "ドア", "문"),
    e("window", "noun", "A1", "Everyday Life", "das Fenster", "окно", "вікно", "la ventana", "la fenêtre", "la finestra", "a janela", "窗户", "窓", "창문"),
    e("street", "noun", "A1", "Travel & Exploration", "die Straße", "улица", "вулиця", "la calle", "la rue", "la strada", "a rua", "街道", "通り", "거리"),
    e("city", "noun", "A1", "Travel & Exploration", "die Stadt", "город", "місто", "la ciudad", "la ville", "la città", "a cidade", "城市", "街", "도시"),
    e("country", "noun", "A1", "Travel & Exploration", "das Land", "страна", "країна", "el país", "le pays", "il paese", "o país", "国家", "国", "나라"),
    e("world", "noun", "A1", "Nature & Environment", "die Welt", "мир", "світ", "el mundo", "le monde", "il mondo", "o mundo", "世界", "世界", "세계"),
    e("school", "noun", "A1", "Society & Culture", "die Schule", "школа", "школа", "la escuela", "l'école", "la scuola", "a escola", "学校", "学校", "학교"),
    e("water", "noun", "A1", "Everyday Life", "das Wasser", "вода", "вода", "el agua", "l'eau", "l'acqua", "a água", "水", "水", "물"),
    e("bread", "noun", "A1", "Everyday Life", "das Brot", "хлеб", "хліб", "el pan", "le pain", "il pane", "o pão", "面包", "パン", "빵"),
    e("food", "noun", "A1", "Everyday Life", "das Essen", "еда", "їжа", "la comida", "la nourriture", "il cibo", "a comida", "食物", "食べ物", "음식"),
    e("coffee", "noun", "A1", "Everyday Life", "der Kaffee", "кофе", "кава", "el café", "le café", "il caffè", "o café", "咖啡", "コーヒー", "커피"),
    e("tea", "noun", "A1", "Everyday Life", "der Tee", "чай", "чай", "el té", "le thé", "il tè", "o chá", "茶", "お茶", "차"),
    e("apple", "noun", "A1", "Everyday Life", "der Apfel", "яблоко", "яблуко", "la manzana", "la pomme", "la mela", "a maçã", "苹果", "リンゴ", "사과"),
    e("time", "noun", "A1", "Everyday Life", "die Zeit", "время", "час", "el tiempo", "le temps", "il tempo", "o tempo", "时间", "時間", "시간"),
    e("day", "noun", "A1", "Everyday Life", "der Tag", "день", "день", "el día", "le jour", "il giorno", "o dia", "天", "日", "날"),
    e("night", "noun", "A1", "Everyday Life", "die Nacht", "ночь", "ніч", "la noche", "la nuit", "la notte", "a noite", "夜晚", "夜", "밤"),
    e("morning", "noun", "A1", "Everyday Life", "der Morgen", "утро", "ранок", "la mañana", "le matin", "la mattina", "a manhã", "早晨", "朝", "아침"),
    e("evening", "noun", "A1", "Everyday Life", "der Abend", "вечер", "вечір", "la tarde", "le soir", "la sera", "a noite", "傍晚", "晩", "저녁"),
    e("year", "noun", "A1", "Everyday Life", "das Jahr", "год", "рік", "el año", "l'année", "l'anno", "o ano", "年", "年", "년"),
    e("month", "noun", "A1", "Everyday Life", "der Monat", "месяц", "місяць", "el mes", "le mois", "il mese", "o mês", "月", "月", "월"),
    e("week", "noun", "A1", "Everyday Life", "die Woche", "неделя", "тиждень", "la semana", "la semaine", "la settimana", "a semana", "周", "週", "주"),
    e("hour", "noun", "A1", "Everyday Life", "die Stunde", "час", "година", "la hora", "l'heure", "l'ora", "a hora", "小时", "時間", "시간"),
    e("minute", "noun", "A1", "Everyday Life", "die Minute", "минута", "хвилина", "el minuto", "la minute", "il minuto", "o minuto", "分钟", "分", "분"),
    e("money", "noun", "A1", "Everyday Life", "das Geld", "деньги", "гроші", "el dinero", "l'argent", "il denaro", "o dinheiro", "钱", "お金", "돈"),
    e("car", "noun", "A1", "Travel & Exploration", "das Auto", "машина", "машина", "el coche", "la voiture", "l'auto", "o carro", "汽车", "車", "차"),
    e("bus", "noun", "A1", "Travel & Exploration", "der Bus", "автобус", "автобус", "el autobús", "le bus", "l'autobus", "o ônibus", "公交车", "バス", "버스"),
    e("train", "noun", "A1", "Travel & Exploration", "der Zug", "поезд", "поїзд", "el tren", "le train", "il treno", "o trem", "火车", "電車", "기차"),
    e("book", "noun", "A1", "Everyday Life", "das Buch", "книга", "книга", "el libro", "le livre", "il libro", "o livro", "书", "本", "책"),
    e("letter", "noun", "A1", "Everyday Life", "der Brief", "письмо", "лист", "la carta", "la lettre", "la lettera", "a carta", "信", "手紙", "편지"),
    e("word", "noun", "A1", "Everyday Life", "das Wort", "слово", "слово", "la palabra", "le mot", "la parola", "a palavra", "词", "言葉", "단어"),
    e("language", "noun", "A1", "Society & Culture", "die Sprache", "язык", "мова", "el idioma", "la langue", "la lingua", "o idioma", "语言", "言語", "언어"),
    e("phone", "noun", "A1", "Everyday Life", "das Telefon", "телефон", "телефон", "el teléfono", "le téléphone", "il telefono", "o telefone", "电话", "電話", "전화"),
    e("table", "noun", "A1", "Everyday Life", "der Tisch", "стол", "стіл", "la mesa", "la table", "il tavolo", "a mesa", "桌子", "机", "탁자"),
    e("chair", "noun", "A1", "Everyday Life", "der Stuhl", "стул", "стілець", "la silla", "la chaise", "la sedia", "a cadeira", "椅子", "椅子", "의자"),
    e("sun", "noun", "A1", "Nature & Environment", "die Sonne", "солнце", "сонце", "el sol", "le soleil", "il sole", "o sol", "太阳", "太陽", "태양"),
    e("rain", "noun", "A1", "Nature & Environment", "der Regen", "дождь", "дощ", "la lluvia", "la pluie", "la pioggia", "a chuva", "雨", "雨", "비"),

    # Core Adjectives
    e("good", "adjective", "A1", "Descriptions & Quality", "gut", "хороший", "хороший", "bueno", "bon", "buono", "bom", "好", "良い", "좋은"),
    e("bad", "adjective", "A1", "Descriptions & Quality", "schlecht", "плохой", "поганий", "malo", "mauvais", "cattivo", "mau", "坏", "悪い", "나쁜"),
    e("big", "adjective", "A1", "Descriptions & Quality", "groß", "большой", "великий", "grande", "grand", "grande", "grande", "大", "大きい", "큰"),
    e("small", "adjective", "A1", "Descriptions & Quality", "klein", "маленький", "маленький", "pequeño", "petit", "piccolo", "pequeno", "小", "小さい", "작은"),
    e("new", "adjective", "A1", "Descriptions & Quality", "neu", "новый", "новий", "nuevo", "nouveau", "nuovo", "novo", "新", "新しい", "새로운"),
    e("old", "adjective", "A1", "Descriptions & Quality", "alt", "старый", "старий", "viejo", "vieux", "vecchio", "velho", "老", "古い", "오래된"),
    e("young", "adjective", "A1", "Descriptions & Quality", "jung", "молодой", "молодий", "joven", "jeune", "giovane", "jovem", "年轻", "若い", "젊은"),
    e("beautiful", "adjective", "A1", "Descriptions & Quality", "schön", "красивый", "гарний", "hermoso", "beau", "bello", "bonito", "美丽", "美しい", "아름다운"),
    e("warm", "adjective", "A1", "Descriptions & Quality", "warm", "тёплый", "теплий", "cálido", "chaud", "caldo", "quente", "温暖", "暖かい", "따뜻한"),
    e("cold", "adjective", "A1", "Descriptions & Quality", "kalt", "холодный", "холодний", "frío", "froid", "freddo", "frio", "寒冷", "寒い", "차가운"),
    e("happy", "adjective", "A1", "Thoughts & Emotions", "glücklich", "счастливый", "щасливий", "feliz", "heureux", "felice", "feliz", "快乐", "幸せな", "행복한"),
    e("fast", "adjective", "A1", "Descriptions & Quality", "schnell", "быстрый", "швидкий", "rápido", "rapide", "veloce", "rápido", "快", "速い", "빠른"),
    e("slow", "adjective", "A1", "Descriptions & Quality", "langsam", "медленный", "повільний", "lento", "lent", "lento", "lento", "慢", "遅い", "느린"),
    e("easy", "adjective", "A1", "Descriptions & Quality", "einfach", "простой", "простий", "fácil", "facile", "facile", "fácil", "简单", "簡単", "쉬운"),
    e("difficult", "adjective", "A1", "Descriptions & Quality", "schwierig", "трудный", "складний", "difícil", "difficile", "difficile", "difícil", "困难", "難しい", "어려운"),
    e("important", "adjective", "A1", "Descriptions & Quality", "wichtig", "важный", "важливий", "importante", "important", "importante", "importante", "重要", "重要", "중요한"),
    e("clean", "adjective", "A1", "Descriptions & Quality", "sauber", "чистый", "чистий", "limpio", "propre", "pulito", "limpo", "干净", "清潔", "깨끗한"),

    # Core Adverbs
    e("now", "adverb", "A1", "Everyday Life", "jetzt", "сейчас", "зараз", "ahora", "maintenant", "ora", "agora", "现在", "今", "지금"),
    e("today", "adverb", "A1", "Everyday Life", "heute", "сегодня", "сьогодні", "hoy", "aujourd'hui", "oggi", "hoje", "今天", "今日", "오늘"),
    e("tomorrow", "adverb", "A1", "Everyday Life", "morgen", "завтра", "завтра", "mañana", "demain", "domani", "amanhã", "明天", "明日", "내일"),
    e("yesterday", "adverb", "A1", "Everyday Life", "gestern", "вчера", "вчора", "ayer", "hier", "ieri", "ontem", "昨天", "昨日", "어제"),
    e("always", "adverb", "A1", "Everyday Life", "immer", "всегда", "завжди", "siempre", "toujours", "sempre", "sempre", "总是", "いつも", "항상"),
    e("never", "adverb", "A1", "Everyday Life", "nie", "никогда", "ніколи", "nunca", "jamais", "mai", "nunca", "从不", "決して", "결코"),
    e("often", "adverb", "A1", "Everyday Life", "oft", "часто", "часто", "a menudo", "souvent", "spesso", "frequentemente", "经常", "よく", "자주"),
    e("very", "adverb", "A1", "Everyday Life", "sehr", "очень", "дуже", "muy", "très", "molto", "muito", "非常", "とても", "매우"),
    e("here", "adverb", "A1", "Everyday Life", "hier", "здесь", "тут", "aquí", "ici", "qui", "aqui", "这里", "ここ", "여기"),
    e("there", "adverb", "A1", "Everyday Life", "dort", "там", "там", "allí", "là", "lì", "lá", "那里", "そこ", "거기")
]

print("A1 Words count:", len(A1_WORDS))
