from vocab_a1 import e

A2_WORDS = [
    # Verbs
    e("to arrive", "verb", "A2", "Travel & Exploration", "ankommen", "прибывать", "прибувати", "llegar", "arriver", "arrivare", "chegar", "到达", "着く", "도착하다"),
    e("to leave", "verb", "A2", "Travel & Exploration", "verlassen", "уходить", "залишати", "salir", "partir", "partire", "partir", "离开", "去る", "떠나다"),
    e("to travel", "verb", "A2", "Travel & Exploration", "reisen", "путешествовать", "подорожувати", "viajar", "voyager", "viaggiare", "viajar", "旅行", "旅行する", "여행하다"),
    e("to stay", "verb", "A2", "Travel & Exploration", "bleiben", "оставаться", "залишатися", "quedarse", "rester", "rimanere", "ficar", "停留", "滞在する", "머물다"),
    e("to visit", "verb", "A2", "Travel & Exploration", "besuchen", "посещать", "відвідувати", "visitar", "visiter", "visitare", "visitar", "参观", "訪れる", "방문하다"),
    e("to invite", "verb", "A2", "Society & Culture", "einladen", "приглашать", "запрошувати", "invitar", "inviter", "invitare", "convidar", "邀请", "招待する", "초대하다"),
    e("to order", "verb", "A2", "Everyday Life", "bestellen", "заказывать", "замовляти", "pedir", "commander", "ordinare", "pedir", "订购", "注文する", "주문하다"),
    e("to choose", "verb", "A2", "Action Verbs", "wählen", "выбирать", "вибирати", "elegir", "choisir", "scegliere", "escolher", "选择", "選ぶ", "선택하다"),
    e("to explain", "verb", "A2", "Action Verbs", "erklären", "объяснять", "пояснювати", "explicar", "expliquer", "spiegare", "explicar", "解释", "説明する", "설명하다"),
    e("to remember", "verb", "A2", "Thoughts & Emotions", "erinnern", "помнить", "пам'ятати", "recordar", "se souvenir", "ricordare", "lembrar", "记得", "思い出す", "기억하다"),
    e("to forget", "verb", "A2", "Thoughts & Emotions", "vergessen", "забывать", "забувати", "olvidar", "oublier", "dimenticare", "esquecer", "忘记", "忘れる", "잊어버리다"),
    e("to lose", "verb", "A2", "Action Verbs", "verlieren", "терять", "втрачати", "perder", "perdre", "perdere", "perder", "丢失", "失う", "잃다"),
    e("to win", "verb", "A2", "Action Verbs", "gewinnen", "выигрывать", "вигравати", "ganar", "gagner", "vincere", "ganhar", "获胜", "勝つ", "이기다"),
    e("to try", "verb", "A2", "Action Verbs", "versuchen", "пробовать", "пробувати", "intentar", "essayer", "provare", "tentar", "尝试", "試す", "시도하다"),
    e("to change", "verb", "A2", "Action Verbs", "ändern", "менять", "змінювати", "cambiar", "changer", "cambiare", "mudar", "改变", "変える", "바꾸다"),
    e("to move", "verb", "A2", "Action Verbs", "bewegen", "двигаться", "рухатися", "mover", "bouger", "muovere", "mover", "移动", "動く", "움직이다"),
    e("to clean", "verb", "A2", "Everyday Life", "putzen", "чистить", "чистити", "limpiar", "nettoyer", "pulire", "limpar", "打扫", "掃除する", "청소하다"),
    e("to cook", "verb", "A2", "Everyday Life", "kochen", "готовить", "готувати", "cocinar", "cuisiner", "cucinare", "cozinhar", "做饭", "料理する", "요리하다"),
    e("to wash", "verb", "A2", "Everyday Life", "waschen", "мыть", "мити", "lavar", "laver", "lavare", "lavar", "洗", "洗う", "씻다"),
    e("to wear", "verb", "A2", "Everyday Life", "tragen", "носить", "носити", "llevar", "porter", "indossare", "vestir", "穿戴", "着る", "입다"),
    e("to prepare", "verb", "A2", "Action Verbs", "vorbereiten", "готовить", "готувати", "preparar", "préparer", "preparare", "preparar", "准备", "準備する", "준비하다"),
    e("to believe", "verb", "A2", "Thoughts & Emotions", "glauben", "верить", "вірити", "creer", "croire", "credere", "acreditar", "相信", "信じる", "믿다"),
    e("to hope", "verb", "A2", "Thoughts & Emotions", "hoffen", "надеяться", "сподіватися", "esperar", "espérer", "sperare", "esperar", "希望", "願う", "바라다"),
    e("to feel", "verb", "A2", "Thoughts & Emotions", "fühlen", "чувствовать", "відчувати", "sentir", "ressentir", "sentire", "sentir", "感觉", "感じる", "느끼다"),
    e("to stop", "verb", "A2", "Action Verbs", "stoppen", "останавливать", "зупиняти", "parar", "arrêter", "fermare", "parar", "停止", "止まる", "멈추다"),
    e("to continue", "verb", "A2", "Action Verbs", "fortsetzen", "продолжать", "продовжувати", "continuar", "continuer", "continuare", "continuar", "继续", "続ける", "계속하다"),
    e("to send", "verb", "A2", "Action Verbs", "senden", "отправлять", "надсилати", "enviar", "envoyer", "inviare", "enviar", "发送", "送る", "보내다"),
    e("to receive", "verb", "A2", "Action Verbs", "erhalten", "получать", "отримувати", "recibir", "recevoir", "ricevere", "receber", "接收", "受け取る", "받다"),
    e("to bring", "verb", "A2", "Action Verbs", "bringen", "приносить", "приносити", "traer", "apporter", "portare", "trazer", "带来", "持ってくる", "가져오다"),
    e("to meet", "verb", "A2", "Society & Culture", "treffen", "встречать", "зустрічати", "conocer", "rencontrer", "incontrare", "encontrar", "遇见", "会う", "만나다"),

    # Nouns
    e("airport", "noun", "A2", "Travel & Exploration", "der Flughafen", "аэропорт", "аеропорт", "el aeropuerto", "l'aéroport", "l'aeroporto", "o aeroporto", "机场", "空港", "공항"),
    e("station", "noun", "A2", "Travel & Exploration", "der Bahnhof", "вокзал", "вокзал", "la estación", "la gare", "la stazione", "a estação", "车站", "駅", "기차역"),
    e("hotel", "noun", "A2", "Travel & Exploration", "das Hotel", "отель", "готель", "el hotel", "l'hôtel", "l'hotel", "o hotel", "酒店", "ホテル", "호텔"),
    e("restaurant", "noun", "A2", "Everyday Life", "das Restaurant", "ресторан", "ресторан", "el restaurante", "le restaurant", "il ristorante", "o restaurante", "餐厅", "レストラン", "식당"),
    e("menu", "noun", "A2", "Everyday Life", "die Speisekarte", "меню", "меню", "el menú", "le menu", "il menu", "o cardápio", "菜单", "メニュー", "메뉴"),
    e("bill", "noun", "A2", "Everyday Life", "die Rechnung", "счёт", "рахунок", "la cuenta", "l'addition", "il conto", "a conta", "账单", "お会計", "계산서"),
    e("market", "noun", "A2", "Everyday Life", "der Markt", "рынок", "ринок", "el mercado", "le marché", "il mercato", "o mercado", "市场", "市場", "시장"),
    e("doctor", "noun", "A2", "Society & Culture", "der Arzt", "врач", "лікар", "el médico", "le médecin", "il medico", "o médico", "医生", "医者", "의사"),
    e("hospital", "noun", "A2", "Society & Culture", "das Krankenhaus", "больница", "лікарня", "el hospital", "l'hôpital", "l'ospedale", "o hospital", "医院", "病院", "병원"),
    e("medicine", "noun", "A2", "Everyday Life", "die Medizin", "лекарство", "ліки", "la medicina", "le médicament", "la medicina", "o remédio", "药物", "薬", "약"),
    e("ticket", "noun", "A2", "Travel & Exploration", "die Fahrkarte", "билет", "квиток", "el billete", "le billet", "il biglietto", "o bilhete", "票", "切符", "표"),
    e("journey", "noun", "A2", "Travel & Exploration", "die Reise", "поездка", "подорож", "el viaje", "le voyage", "il viaggio", "a viagem", "旅行", "旅", "여행"),
    e("vacation", "noun", "A2", "Travel & Exploration", "der Urlaub", "отпуск", "відпустка", "las vacaciones", "les vacances", "le vacanze", "as férias", "假期", "休暇", "휴가"),
    e("luggage", "noun", "A2", "Travel & Exploration", "das Gepäck", "багаж", "багаж", "el equipaje", "les bagages", "il bagaglio", "a bagagem", "行李", "荷物", "짐"),
    e("weather", "noun", "A2", "Nature & Environment", "das Wetter", "погода", "погода", "el tiempo", "la météo", "il tempo", "o clima", "天气", "天気", "날씨"),
    e("snow", "noun", "A2", "Nature & Environment", "der Schnee", "снег", "сніг", "la nieve", "la neige", "la neve", "a neve", "雪", "雪", "눈"),
    e("summer", "noun", "A2", "Nature & Environment", "der Sommer", "лето", "літо", "el verano", "l'été", "l'estate", "o verão", "夏天", "夏", "여름"),
    e("winter", "noun", "A2", "Nature & Environment", "der Winter", "зима", "зима", "el invierno", "l'hiver", "l'inverno", "o inverno", "冬天", "冬", "겨울"),
    e("clothes", "noun", "A2", "Everyday Life", "die Kleidung", "одежда", "одяг", "la ropa", "les vêtements", "i vestiti", "as roupas", "衣服", "服", "옷"),
    e("shoes", "noun", "A2", "Everyday Life", "die Schuhe", "обувь", "взуття", "los zapatos", "les chaussures", "le scarpe", "os sapatos", "鞋子", "靴", "신발"),
    e("price", "noun", "A2", "Everyday Life", "der Preis", "цена", "ціна", "el precio", "le prix", "il prezzo", "o preço", "价格", "価格", "가격"),
    e("music", "noun", "A2", "Society & Culture", "die Musik", "музыка", "музика", "la música", "la musique", "la musica", "a música", "音乐", "音楽", "음악"),
    e("film", "noun", "A2", "Society & Culture", "der Film", "фильм", "фільм", "la película", "le film", "il film", "o filme", "电影", "映画", "영화"),
    e("party", "noun", "A2", "Society & Culture", "die Party", "вечеринка", "вечірка", "la fiesta", "la fête", "la festa", "a festa", "聚会", "パーティー", "파티"),
    e("gift", "noun", "A2", "Everyday Life", "das Geschenk", "подарок", "подарунок", "el regalo", "le cadeau", "il regalo", "o presente", "礼物", "プレゼント", "선물"),
    e("neighbor", "noun", "A2", "Society & Culture", "der Nachbar", "сосед", "сусід", "el vecino", "le voisin", "il vicino", "o vizinho", "邻居", "隣人", "이웃"),
    e("colleague", "noun", "A2", "Professional & Tech", "der Kollege", "коллега", "колега", "el colega", "le collègue", "il collega", "o colega", "同事", "同僚", "동료"),
    e("problem", "noun", "A2", "Everyday Life", "das Problem", "проблема", "проблема", "el problema", "le problème", "il problema", "o problema", "问题", "問題", "문제"),
    e("solution", "noun", "A2", "Everyday Life", "die Lösung", "решение", "рішення", "la solución", "la solution", "la soluzione", "a solução", "解决方案", "解決策", "해결책"),
    e("nature", "noun", "A2", "Nature & Environment", "die Natur", "природа", "природа", "la naturaleza", "la nature", "la natura", "a natureza", "大自然", "自然", "자연"),
    e("dog", "noun", "A2", "Nature & Environment", "der Hund", "собака", "собака", "el perro", "le chien", "il cane", "o cão", "狗", "犬", "개"),
    e("cat", "noun", "A2", "Nature & Environment", "die Katze", "кошка", "кішка", "el gato", "le chat", "il gatto", "o gato", "猫", "猫", "고양이"),
    e("flower", "noun", "A2", "Nature & Environment", "die Blume", "цветок", "квітка", "la flor", "la fleur", "il fiore", "a flor", "花朵", "花", "꽃"),
    e("sea", "noun", "A2", "Nature & Environment", "das Meer", "море", "море", "el mar", "la mer", "il mare", "o mar", "大海", "海", "바다"),
    e("mountain", "noun", "A2", "Nature & Environment", "der Berg", "гора", "гора", "la montaña", "la montagne", "la montagna", "a montanha", "山峰", "山", "산"),

    # Adjectives
    e("interesting", "adjective", "A2", "Descriptions & Quality", "interessant", "интересный", "цікавий", "interesante", "intéressant", "interessante", "interessante", "有趣", "面白い", "흥미로운"),
    e("boring", "adjective", "A2", "Descriptions & Quality", "langweilig", "скучный", "нудний", "aburrido", "ennuyeux", "noioso", "chato", "无聊", "退屈な", "지루한"),
    e("friendly", "adjective", "A2", "Thoughts & Emotions", "freundlich", "дружелюбный", "дружній", "amable", "amical", "amichevole", "amigável", "友好", "親切な", "친절한"),
    e("funny", "adjective", "A2", "Thoughts & Emotions", "lustig", "смешной", "смішний", "divertido", "drôle", "divertente", "engraçado", "有趣", "面白い", "재미있는"),
    e("safe", "adjective", "A2", "Descriptions & Quality", "sicher", "безопасный", "безпечний", "seguro", "sûr", "sicuro", "seguro", "安全", "安全な", "안전한"),
    e("healthy", "adjective", "A2", "Descriptions & Quality", "gesund", "здоровый", "здоровий", "sano", "sain", "sano", "saudável", "健康", "健康な", "건강한"),
    e("useful", "adjective", "A2", "Descriptions & Quality", "nützlich", "полезный", "корисний", "útil", "utile", "utile", "útil", "有用", "役に立つ", "유용한"),
    e("tired", "adjective", "A2", "Thoughts & Emotions", "müde", "уставший", "втомлений", "cansado", "fatigué", "stanco", "cansado", "疲倦", "疲れた", "피곤한"),
    e("possible", "adjective", "A2", "Descriptions & Quality", "möglich", "возможный", "можливий", "posible", "possible", "possibile", "possível", "可能", "可能", "가능한"),
    e("popular", "adjective", "A2", "Descriptions & Quality", "beliebt", "популярный", "популярний", "popular", "populaire", "popolare", "popular", "受欢迎", "人気のある", "인기 있는"),
    e("modern", "adjective", "A2", "Descriptions & Quality", "modern", "современный", "сучасний", "moderno", "moderne", "moderno", "moderno", "现代", "現代的", "현대적인"),
    e("delicious", "adjective", "A2", "Descriptions & Quality", "lecker", "вкусный", "смачний", "delicioso", "délicieux", "delizioso", "delicioso", "美味", "美味しい", "맛있는"),
    e("comfortable", "adjective", "A2", "Descriptions & Quality", "bequem", "удобный", "зручний", "cómodo", "confortable", "comodo", "confortável", "舒适", "快適な", "편안한"),
    e("bright", "adjective", "A2", "Descriptions & Quality", "hell", "яркий", "яскравий", "brillante", "lumineux", "luminoso", "brilhante", "明亮", "明るい", "밝은"),
    e("strong", "adjective", "A2", "Descriptions & Quality", "stark", "сильный", "сильний", "fuerte", "fort", "forte", "forte", "强壮", "強い", "강한"),

    # Adverbs
    e("perhaps", "adverb", "A2", "Everyday Life", "vielleicht", "может быть", "можливо", "quizás", "peut-être", "forse", "talvez", "也许", "たぶん", "아마도"),
    e("almost", "adverb", "A2", "Everyday Life", "fast", "почти", "майже", "casi", "presque", "quasi", "quase", "几乎", "ほとんど", "거의"),
    e("especially", "adverb", "A2", "Everyday Life", "besonders", "особенно", "особливо", "especialmente", "surtout", "soprattutto", "especialmente", "特别", "特に", "특히"),
    e("soon", "adverb", "A2", "Everyday Life", "bald", "скоро", "скоро", "pronto", "bientôt", "presto", "em breve", "很快", "まもなく", "곧"),
    e("clearly", "adverb", "A2", "Everyday Life", "deutlich", "ясно", "чітко", "claramente", "clairement", "chiaramente", "claramente", "清楚", "はっきりと", "분명히"),
    e("usually", "adverb", "A2", "Everyday Life", "gewöhnlich", "обычно", "зазвичай", "usualmente", "d'habitude", "di solito", "geralmente", "通常", "普段", "보통"),
    e("suddenly", "adverb", "A2", "Everyday Life", "plötzlich", "внезапно", "раптово", "de repente", "soudain", "all'improvviso", "de repente", "突然", "突然", "갑자기"),
    e("enough", "adverb", "A2", "Everyday Life", "genug", "достаточно", "достатньо", "suficiente", "assez", "abbastanza", "bastante", "足够", "十分に", "충분히")
]

print("A2 Words count:", len(A2_WORDS))
