from vocab_a1 import e

FINAL_WORDS = [
    # C1/C2 Nuances & Idiomatic Essentials
    e("premise", "noun", "C1", "Thoughts & Emotions", "die Prämisse", "предпосылка", "передумова", "la premisa", "la prémisse", "la premessa", "a premissa", "前提", "前提", "전제"),
    e("rhetoric", "noun", "C1", "Society & Culture", "die Rhetorik", "риторика", "риторика", "la retórica", "la rhétorique", "la retorica", "a retórica", "修辞", "修辞学", "수사학"),
    e("integrity", "noun", "C1", "Thoughts & Emotions", "die Integrität", "честность", "чесність", "la integridad", "l'intégrité", "l'integrità", "a integridade", "正直/完整", "高潔", "진실성"),
    e("legacy", "noun", "C1", "Society & Culture", "das Erbe", "наследие", "спадщина", "el legado", "le legs", "l'eredità", "o legado", "遗产", "遺産", "유산"),
    e("sovereignty", "noun", "C1", "Society & Culture", "die Souveränität", "суверенитет", "суверенітет", "la soberanía", "la souveraineté", "la sovranità", "a soberania", "主权", "主権", "주권"),
    e("catalyst", "noun", "C1", "Nature & Environment", "der Katalysator", "катализатор", "каталізатор", "el catalizador", "le catalyseur", "il catalizzatore", "o catalisador", "催化剂", "触媒", "촉매"),
    e("zenith", "noun", "C1", "Nature & Environment", "der Zenit", "зенит", "зеніт", "el cenit", "le zénith", "lo zenit", "o zênite", "顶点", "頂点", "정점"),
    e("fragile", "adjective", "C1", "Descriptions & Quality", "zerbrechlich", "хрупкий", "крихкий", "frágil", "fragile", "fragile", "frágil", "脆弱的", "壊れやすい", "취약한"),
    e("volatile", "adjective", "C1", "Descriptions & Quality", "flüchtig", "изменчивый", "мінливий", "volátil", "volatil", "volatile", "volátil", "挥发性/不稳定的", "変動しやすい", "휘발성의"),
    e("tangible", "adjective", "C1", "Descriptions & Quality", "greifbar", "осязаемый", "відчутний", "tangible", "tangible", "tangibile", "tangível", "有形的", "明白な", "유형의"),
    e("implicit", "adjective", "C1", "Thoughts & Emotions", "implizit", "подразумеваемый", "неявний", "implícito", "implicite", "implicito", "implícito", "含蓄的", "暗黙の", "암시적인"),
    e("explicit", "adjective", "C1", "Thoughts & Emotions", "explizit", "явный", "явний", "explícito", "explicite", "esplicito", "explícito", "明确的", "明白な", "명시적인"),
    e("exhaustive", "adjective", "C1", "Descriptions & Quality", "erschöpfend", "исчерпывающий", "вичерпний", "exhaustivo", "exhaustif", "esaustivo", "exaustivo", "详尽的", "徹底的な", "철저한"),
    e("multifaceted", "adjective", "C1", "Descriptions & Quality", "facettenreich", "многогранный", "багатогранний", "multifacético", "aux multiples facettes", "sfaccettato", "multifacetado", "多层面的", "多面的な", "다면적인"),
    e("perpetual", "adjective", "C1", "Descriptions & Quality", "ewig", "вечный", "вічний", "perpetuo", "perpétuel", "perpetuo", "perpétuo", "永恒的", "永続的な", "영구적인"),
    e("virtually", "adverb", "C1", "Everyday Life", "praktisch", "практически", "практично", "virtualmente", "virtuellement", "virtualmente", "virtualmente", "实际上", "実質的に", "사실상"),
    e("merely", "adverb", "C1", "Everyday Life", "lediglich", "всего лишь", "лише", "simplemente", "simplement", "semplicemente", "meramente", "仅仅", "単に", "단지"),
    e("exquisitely", "adverb", "C1", "Descriptions & Quality", "vorzüglich", "изысканно", "вишукано", "exquisitamente", "exquise", "squisitamente", "exquisitamente", "精美地", "見事に", "정교하게"),

    # C2 Mastery Entries
    e("causality", "noun", "C2", "Thoughts & Emotions", "die Kausalität", "причинность", "причинність", "la causalidad", "la causalité", "la causalità", "a causalidade", "因果关系", "因果関係", "인과관계"),
    e("aesthetics", "noun", "C2", "Society & Culture", "die Ästhetik", "эстетика", "естетика", "la estética", "l'esthétique", "l'estetica", "a estética", "美学", "美学", "미학"),
    e("quintessence", "noun", "C2", "Thoughts & Emotions", "die Quintessenz", "квинтэссенция", "квінтесенція", "la quintaesencia", "la quintessence", "la quintessenza", "a quintessência", "精髓", "真髄", "정수"),
    e("discourse", "noun", "C2", "Society & Culture", "der Diskurs", "дискурс", "дискурс", "el discurso", "le discours", "il discorso", "o discurso", "话语/论述", "言説", "담론"),
    e("juxtaposition", "noun", "C2", "Descriptions & Quality", "die Gegenüberstellung", "сопоставление", "зіставлення", "la yuxtaposición", "la juxtaposition", "la contrapposizione", "a justaposição", "并列", "並置", "병치"),
    e("veracity", "noun", "C2", "Thoughts & Emotions", "die Wahrhaftigkeit", "достоверность", "правдивість", "la veracidad", "la véracité", "la veridicità", "a veracidade", "真实性", "真実性", "진실성"),
    e("oblivion", "noun", "C2", "Thoughts & Emotions", "das Vergessen", "забвение", "забуття", "el olvido", "l'oubli", "l'oblio", "o esquecimento", "遗忘", "忘却", "망각"),
    e("lucid", "adjective", "C2", "Thoughts & Emotions", "klar", "ясный", "ясний", "lúcido", "lucide", "lucido", "lúcido", "清晰的", "明快な", "명료한"),
    e("paramount", "adjective", "C2", "Descriptions & Quality", "überragend", "первостепенный", "першорядний", "primordial", "primordial", "primordiale", "primordial", "至高无上的", "最高の", "가장 중요한"),
    e("indomitable", "adjective", "C2", "Thoughts & Emotions", "unbezwingbar", "неукротимый", "непохитний", "indomable", "indomptable", "indomabile", "indomável", "不屈的", "不屈の", "불굴의"),
    e("immaculate", "adjective", "C2", "Descriptions & Quality", "tadellos", "безупречный", "бездоганний", "inmaculado", "immaculé", "immacolato", "imaculado", "纯洁无瑕的", "汚れのない", "결점 없는"),
    e("ubiquitous", "adjective", "C2", "Descriptions & Quality", "allgegenwärtig", "вездесущий", "всюдисущий", "ubicuo", "omniprésent", "onnipresenziale", "onipresente", "无处不在的", "偏在する", "어디에나 있는"),
    e("infallible", "adjective", "C2", "Descriptions & Quality", "unfehlbar", "непогрешимый", "безпомилковий", "infalible", "infaillible", "infallibile", "infalível", "绝不犯错的", "誤りのない", "틀림없는"),
    e("pristine", "adjective", "C2", "Descriptions & Quality", "makellos", "первозданный", "незайманий", "prístino", "immaculé", "incontaminato", "impecável", "原始纯洁的", "素朴な", "원시 그대로의"),
    e("arguably", "adverb", "C2", "Thoughts & Emotions", "wohl", "возможно", "можливо", "posiblemente", "sans doute", "probabilmente", "provavelmente", "可以认为是", "おそらく", "거의 틀림없이"),
    e("incontrovertibly", "adverb", "C2", "Thoughts & Emotions", "unwiderlegbar", "неопровержимо", "незаперечно", "incontrovertiblemente", "irréfutablement", "incontrovertibilmente", "incontrovertivelmente", "无可争议地", "議論の余地なく", "명백히"),

    # Additional high frequency A1-B1 words to guarantee smooth learning
    e("music player", "noun", "A2", "Everyday Life", "der Musikspieler", "музыкальный плеер", "музичний плеєр", "el reproductor", "le lecteur de musique", "il lettore musicale", "o reprodutor", "播放器", "プレーヤー", "음악 플레이어"),
    e("camera", "noun", "A2", "Everyday Life", "die Kamera", "фотоаппарат", "камера", "la cámara", "l'appareil photo", "la fotocamera", "a câmera", "照相机", "カメラ", "카메라"),
    e("screen", "noun", "A2", "Professional & Tech", "der Bildschirm", "экран", "екран", "la pantalla", "l'écran", "lo schermo", "a tela", "屏幕", "画面", "화면"),
    e("keyboard", "noun", "A2", "Professional & Tech", "die Tastatur", "клавиатура", "клавіатура", "el teclado", "le clavier", "la tastiera", "o teclado", "键盘", "キーボード", "키보드"),
    e("mouse", "noun", "A2", "Professional & Tech", "die Maus", "мышь", "миша", "el ratón", "la souris", "il mouse", "o mouse", "鼠标", "マウス", "마우스"),
    e("library", "noun", "A2", "Society & Culture", "die Bibliothek", "библиотека", "бібліотека", "la biblioteca", "la bibliothèque", "la biblioteca", "a biblioteca", "图书馆", "図書館", "도서관"),
    e("museum", "noun", "A2", "Society & Culture", "das Museum", "музей", "музей", "el museo", "le musée", "il museo", "o museu", "博物馆", "博物館", "박물관"),
    e("theater", "noun", "A2", "Society & Culture", "das Theater", "театр", "театр", "el teatro", "le théâtre", "il teatro", "o teatro", "剧院", "劇場", "극장"),
    e("cinema", "noun", "A2", "Society & Culture", "das Kino", "кинотеатр", "кінотеатр", "el cine", "le cinéma", "il cinema", "o cinema", "电影院", "映画館", "영화관"),
    e("pharmacy", "noun", "A2", "Everyday Life", "die Apotheke", "аптека", "аптека", "la farmacia", "la pharmacie", "la farmacia", "a farmácia", "药店", "薬局", "약국"),
    e("bank", "noun", "A2", "Everyday Life", "die Bank", "банк", "банк", "el banco", "la banque", "la banca", "o banco", "银行", "銀行", "은행"),
    e("post office", "noun", "A2", "Everyday Life", "die Post", "почта", "пошта", "la oficina de correos", "la poste", "l'ufficio postale", "os correios", "邮局", "郵便局", "우체국"),
    e("police", "noun", "A2", "Society & Culture", "die Polizei", "полиция", "поліція", "la policía", "la police", "la polizia", "a polícia", "警察", "警察", "경찰"),
    e("fire station", "noun", "A2", "Society & Culture", "die Feuerwehr", "пожарная служба", "пожежна служба", "los bomberos", "les pompiers", "i vigili del fuoco", "os bombeiros", "消防局", "消防署", "소방서"),
    e("bridge", "noun", "A2", "Travel & Exploration", "die Brücke", "мост", "міст", "el puente", "le pont", "il ponte", "a ponte", "桥梁", "橋", "다리"),
    e("park", "noun", "A2", "Nature & Environment", "der Park", "парк", "парк", "el parque", "le parc", "il parco", "o parque", "公园", "公園", "공원"),
    e("lake", "noun", "A2", "Nature & Environment", "der See", "озеро", "озеро", "el lago", "le lac", "il lago", "o lago", "湖泊", "湖", "호수"),
    e("river", "noun", "A2", "Nature & Environment", "der Fluss", "река", "річка", "el río", "le fleuve", "il fiume", "o rio", "河流", "川", "강"),
    e("forest", "noun", "A2", "Nature & Environment", "der Wald", "лес", "ліс", "el bosque", "la forêt", "la foresta", "a floresta", "森林", "森", "숲"),
    e("village", "noun", "A2", "Travel & Exploration", "das Dorf", "деревня", "село", "el pueblo", "le village", "il villaggio", "a vila", "村庄", "村", "마을"),
    e("building", "noun", "A2", "Travel & Exploration", "das Gebäude", "здание", "будівля", "el edificio", "le bâtiment", "l'edificio", "o edifício", "建筑物", "建物", "건물"),
    e("square", "noun", "A2", "Travel & Exploration", "der Platz", "площадь", "площа", "la plaza", "la place", "la piazza", "a praça", "广场", "広場", "광장"),
    e("corner", "noun", "A2", "Travel & Exploration", "die Ecke", "угол", "кут", "la esquina", "le coin", "l'angolo", "a esquina", "角落", "角", "모퉁이"),
    e("map", "noun", "A2", "Travel & Exploration", "die Karte", "карта", "карта", "el mapa", "la carte", "la mappa", "o mapa", "地图", "地図", "지도"),
    e("passport", "noun", "A2", "Travel & Exploration", "der Reisepass", "паспорт", "паспорт", "el pasaporte", "le passeport", "il passaporto", "o passaporte", "护照", "パスポート", "여권"),
    e("to reserve", "verb", "A2", "Travel & Exploration", "reservieren", "бронировать", "бронювати", "reservar", "réserver", "prenotare", "reservar", "预订", "予約する", "예약하다"),
    e("to confirm", "verb", "A2", "Professional & Tech", "bestätigen", "подтверждать", "підтверджувати", "confirmar", "confirmer", "confermare", "confirmar", "确认", "確認する", "확인하다"),
    e("to cancel", "verb", "A2", "Everyday Life", "stornieren", "отменять", "скасовувати", "cancelar", "annuler", "cancellare", "cancelar", "取消", "キャンセルする", "취소하다"),
    e("to invite", "verb", "A2", "Society & Culture", "einladen", "приглашать", "запрошувати", "invitar", "inviter", "invitare", "convidar", "邀请", "招待する", "초대하다"),
    e("to celebrate", "verb", "A2", "Society & Culture", "feiern", "праздновать", "святкувати", "celebrar", "célébrer", "festeggiare", "celebrar", "庆祝", "祝う", "축하하다"),
    e("to recommend", "verb", "B1", "Society & Culture", "empfehlen", "рекомендовать", "рекомендувати", "recomendar", "recommander", "raccomandare", "recomendar", "推荐", "勧める", "추천하다"),
    e("to complain", "verb", "B1", "Everyday Life", "beschweren", "жаловаться", "скаржитися", "quejarse", "se plaindre", "lamentarsi", "reclamar", "抱怨", "苦情を言う", "불평하다"),
    e("to replace", "verb", "B1", "Action Verbs", "ersetzen", "заменять", "замінювати", "reemplazar", "remplacer", "sostituire", "substituir", "替换", "置き換える", "대체하다"),
    e("to belong", "verb", "B1", "Thoughts & Emotions", "gehören", "принадлежать", "належати", "pertenecer", "appartenir", "appartenere", "pertencer", "属于", "属する", "속하다")
]

print("Final Words count:", len(FINAL_WORDS))
