from vocab_a1 import e

EXPANSION_WORDS = [
    # More A1/A2 Nouns & Verbs
    e("tea", "noun", "A1", "Everyday Life", "der Tee", "чай", "чай", "el té", "le thé", "il tè", "o chá", "茶", "お茶", "차"),
    e("milk", "noun", "A1", "Everyday Life", "die Milch", "молоко", "молоко", "la leche", "le lait", "il latte", "o leite", "牛奶", "牛乳", "우유"),
    e("sugar", "noun", "A1", "Everyday Life", "der Zucker", "сахар", "цукор", "el azúcar", "le sucre", "lo zucchero", "o açúcar", "糖", "砂糖", "설탕"),
    e("salt", "noun", "A1", "Everyday Life", "das Salz", "соль", "сіль", "la sal", "le sel", "il sale", "o sal", "盐", "塩", "소금"),
    e("fruit", "noun", "A1", "Everyday Life", "das Obst", "фрукты", "фрукти", "la fruta", "le fruit", "la frutta", "a fruta", "水果", "果物", "과일"),
    e("vegetable", "noun", "A1", "Everyday Life", "das Gemüse", "овощи", "овочі", "la verdura", "le légume", "la verdura", "o legume", "蔬菜", "野菜", "야채"),
    e("kitchen", "noun", "A1", "Everyday Life", "die Küche", "кухня", "кухня", "la cocina", "la cuisine", "la cucina", "a cozinha", "厨房", "キッチン", "주방"),
    e("bathroom", "noun", "A1", "Everyday Life", "das Badezimmer", "ванная комната", "ванна кімната", "el baño", "la salle de bain", "il bagno", "o banheiro", "浴室", "浴室", "욕실"),
    e("bed", "noun", "A1", "Everyday Life", "das Bett", "кровать", "ліжко", "la cama", "le lit", "il letto", "a cama", "床", "ベッド", "침대"),
    e("garden", "noun", "A1", "Nature & Environment", "der Garten", "сад", "сад", "el jardín", "le jardin", "il giardino", "o jardim", "花园", "庭", "정원"),
    e("tree", "noun", "A1", "Nature & Environment", "der Baum", "дерево", "дерево", "el árbol", "l'arbre", "l'albero", "a árvore", "树", "木", "나무"),
    e("bird", "noun", "A1", "Nature & Environment", "der Vogel", "птица", "птах", "el pájaro", "l'oiseau", "l'uccello", "o pássaro", "鸟", "鳥", "새"),
    e("sky", "noun", "A1", "Nature & Environment", "der Himmel", "небо", "небо", "el cielo", "le ciel", "il cielo", "o céu", "天空", "空", "하늘"),
    e("moon", "noun", "A1", "Nature & Environment", "der Mond", "луна", "місяць", "la luna", "la lune", "la luna", "a lua", "月亮", "月", "달"),
    e("star", "noun", "A1", "Nature & Environment", "der Stern", "звезда", "зірка", "la estrella", "l'étoile", "la stella", "a estrela", "星星", "星", "별"),
    e("wind", "noun", "A1", "Nature & Environment", "der Wind", "ветер", "вітер", "el viento", "le vent", "il vento", "o vento", "风", "風", "바람"),
    e("morning", "noun", "A1", "Everyday Life", "der Morgen", "утро", "ранок", "la mañana", "le matin", "la mattina", "a manhã", "早晨", "朝", "아침"),
    e("afternoon", "noun", "A1", "Everyday Life", "der Nachmittag", "день", "день", "la tarde", "l'après-midi", "il pomeriggio", "a tarde", "下午", "午後", "오후"),
    e("evening", "noun", "A1", "Everyday Life", "der Abend", "вечер", "вечір", "la tarde", "le soir", "la sera", "a noite", "晚上", "晩", "저녁"),
    e("midnight", "noun", "A1", "Everyday Life", "die Mitternacht", "полночь", "північ", "la medianoche", "le minuit", "la mezzanotte", "a meia-noite", "午夜", "真夜中", "자정"),
    e("clock", "noun", "A1", "Everyday Life", "die Uhr", "часы", "годинник", "el reloj", "l'horloge", "l'orologio", "o relógio", "钟表", "時計", "시계"),
    e("key", "noun", "A1", "Everyday Life", "der Schlüssel", "ключ", "ключ", "la llave", "la clé", "la chiave", "a chave", "钥匙", "鍵", "열쇠"),
    e("bag", "noun", "A1", "Everyday Life", "die Tasche", "сумка", "сумка", "la bolsa", "le sac", "la borsa", "a bolsa", "包", "バッグ", "가방"),
    e("coat", "noun", "A1", "Everyday Life", "der Mantel", "пальто", "пальто", "el abrigo", "le manteau", "il cappotto", "o casaco", "大衣", "コート", "코트"),
    e("hat", "noun", "A1", "Everyday Life", "der Hut", "шляпа", "капелюх", "el sombrero", "le chapeau", "il cappello", "o chapéu", "帽子", "帽子", "모자"),
    e("pen", "noun", "A1", "Everyday Life", "der Stift", "ручка", "ручка", "el bolígrafo", "le stylo", "la penna", "a caneta", "笔", "ペン", "펜"),
    e("paper", "noun", "A1", "Everyday Life", "das Papier", "бумага", "папір", "el papel", "le papier", "la carta", "o papel", "纸", "紙", "종이"),
    e("newspaper", "noun", "A1", "Everyday Life", "die Zeitung", "газета", "газета", "el periódico", "le journal", "il giornale", "o jornal", "报纸", "新聞", "신문"),
    e("picture", "noun", "A1", "Everyday Life", "das Bild", "картина", "картина", "el cuadro", "le tableau", "il quadro", "o quadro", "画", "絵", "그림"),
    e("color", "noun", "A1", "Descriptions & Quality", "die Farbe", "цвет", "колір", "el color", "la couleur", "il colore", "a cor", "颜色", "色", "색상"),
    e("red", "adjective", "A1", "Descriptions & Quality", "rot", "красный", "червоний", "rojo", "rouge", "rosso", "vermelho", "红色", "赤", "빨간색"),
    e("blue", "adjective", "A1", "Descriptions & Quality", "blau", "синий", "синій", "azul", "bleu", "blu", "azul", "蓝色", "青", "파란색"),
    e("green", "adjective", "A1", "Descriptions & Quality", "grün", "зелёный", "зелений", "verde", "vert", "verde", "verde", "绿色", "緑", "초록색"),
    e("yellow", "adjective", "A1", "Descriptions & Quality", "gelb", "жёлтый", "жовтий", "amarillo", "jaune", "giallo", "amarelo", "黄色", "黄色", "노란색"),
    e("white", "adjective", "A1", "Descriptions & Quality", "weiß", "белый", "білий", "blanco", "blanc", "bianco", "branco", "白色", "白", "흰색"),
    e("black", "adjective", "A1", "Descriptions & Quality", "schwarz", "чёрный", "чорний", "negro", "noir", "nero", "preto", "黑色", "黒", "검은색"),

    # More A2/B1 Everyday & Communication
    e("to build", "verb", "A2", "Action Verbs", "bauen", "строить", "будувати", "construir", "construire", "costruire", "construir", "建造", "建てる", "짓다"),
    e("to cut", "verb", "A2", "Action Verbs", "schneiden", "резать", "різати", "cortar", "couper", "tagliare", "cortar", "切", "切る", "자르다"),
    e("to draw", "verb", "A2", "Action Verbs", "zeichnen", "рисовать", "малювати", "dibujar", "dessiner", "disegnare", "desenhar", "绘画", "描く", "그리다"),
    e("to sing", "verb", "A2", "Action Verbs", "singen", "петь", "співати", "cantar", "chanter", "cantare", "cantar", "唱歌", "歌う", "노래하다"),
    e("to dance", "verb", "A2", "Action Verbs", "tanzen", "танцевать", "танцювати", "bailar", "danser", "ballare", "dançar", "跳舞", "踊る", "춤추다"),
    e("to smile", "verb", "A2", "Thoughts & Emotions", "lächeln", "улыбаться", "посміхатися", "sonreír", "sourire", "sorridere", "sorrir", "微笑", "微笑む", "미소 짓다"),
    e("to laugh", "verb", "A2", "Thoughts & Emotions", "lachen", "смеяться", "сміятися", "reír", "rire", "ridere", "rir", "笑", "笑う", "웃다"),
    e("to cry", "verb", "A2", "Thoughts & Emotions", "weinen", "плакать", "плакати", "llorar", "pleurer", "piangere", "chorar", "哭泣", "泣く", "울다"),
    e("to carry", "verb", "A2", "Action Verbs", "tragen", "носить", "носити", "llevar", "porter", "portare", "carregar", "搬运", "運ぶ", "나르다"),
    e("to pull", "verb", "A2", "Action Verbs", "ziehen", "тянуть", "тягти", "tirar", "tirer", "tirare", "puxar", "拉", "引く", "당기다"),
    e("to push", "verb", "A2", "Action Verbs", "drücken", "толкать", "штовхати", "empujar", "pousser", "spingere", "empurrar", "推", "押す", "밀다"),
    e("to throw", "verb", "A2", "Action Verbs", "werfen", "бросать", "кидати", "lanzar", "lancer", "lanciare", "jogar", "扔", "投げる", "던지다"),
    e("to catch", "verb", "A2", "Action Verbs", "fangen", "ловить", "ловити", "atrapar", "attraper", "afferrare", "pegar", "抓住", "捕まえる", "잡다"),
    e("to fly", "verb", "A2", "Action Verbs", "fliegen", "летать", "літати", "volar", "voler", "volare", "voar", "飞", "飛ぶ", "날다"),
    e("to drive", "verb", "A2", "Action Verbs", "fahren", "водить", "керувати", "conducir", "conduire", "guidare", "dirigir", "驾驶", "運転する", "운전하다"),
    e("to swim", "verb", "A2", "Action Verbs", "schwimmen", "плавать", "плавати", "nadar", "nager", "nuotare", "nadar", "游泳", "泳ぐ", "수영하다"),
    e("to run", "verb", "A2", "Action Verbs", "laufen", "бегать", "бігати", "correr", "courir", "correre", "correr", "跑步", "走る", "달리다"),
    e("to fall", "verb", "A2", "Action Verbs", "fallen", "падать", "падати", "caer", "tomber", "cadere", "cair", "跌倒", "落ちる", "떨어지다"),
    e("to stand", "verb", "A2", "Action Verbs", "stehen", "стоять", "стояти", "estar de pie", "être debout", "stare in piedi", "ficar de pé", "站立", "立つ", "서다"),
    e("to sit", "verb", "A2", "Action Verbs", "sitzen", "сидеть", "сидіти", "sentarse", "s'asseoir", "sedersi", "sentar-se", "坐", "座る", "앉다"),

    # B1/B2 Concepts
    e("memory", "noun", "B1", "Thoughts & Emotions", "die Erinnerung", "память", "пам'ять", "el recuerdo", "le souvenir", "il ricordo", "a lembrança", "记忆", "記憶", "기억"),
    e("habit", "noun", "B1", "Everyday Life", "die Gewohnheit", "привычка", "звичка", "el hábito", "l'habitude", "l'abitudine", "o hábito", "习惯", "習慣", "습관"),
    e("progress", "noun", "B1", "Professional & Tech", "der Fortschritt", "прогресс", "прогрес", "el progreso", "le progrès", "il progresso", "o progresso", "进步", "進歩", "진보"),
    e("danger", "noun", "B1", "Everyday Life", "die Gefahr", "опасность", "небезпека", "el peligro", "le danger", "il pericolo", "o perigo", "危险", "危険", "위험"),
    e("attention", "noun", "B1", "Thoughts & Emotions", "die Aufmerksamkeit", "внимание", "увага", "la atención", "l'attention", "l'attenzione", "a atenção", "注意", "注意", "주의"),
    e("difference", "noun", "B1", "Thoughts & Emotions", "der Unterschied", "различие", "різниця", "la diferencia", "la différence", "la differenza", "a diferença", "差异", "違い", "차이"),
    e("community", "noun", "B1", "Society & Culture", "die Gemeinschaft", "сообщество", "спільнота", "la comunidad", "la communauté", "la comunità", "a comunidade", "社区", "共同体", "공동체"),
    e("quality", "noun", "B1", "Descriptions & Quality", "die Qualität", "качество", "якість", "la calidad", "la qualité", "la qualità", "a qualidade", "质量", "品質", "품질"),
    e("condition", "noun", "B1", "Everyday Life", "die Bedingung", "условие", "умова", "la condición", "la condition", "la condizione", "a condição", "条件", "条件", "조건"),
    e("choice", "noun", "B1", "Thoughts & Emotions", "die Wahl", "выбор", "вибір", "la elección", "le choix", "la scelta", "a escolha", "选择", "選択", "선택"),
    e("imagination", "noun", "B1", "Thoughts & Emotions", "die Fantasie", "воображение", "уява", "la imaginación", "l'imagination", "l'immaginazione", "a imaginação", "想象力", "想像力", "상상력"),
    e("attitude", "noun", "B1", "Thoughts & Emotions", "die Einstellung", "отношение", "ставлення", "la actitud", "l'attitude", "l'atteggiamento", "a atitude", "态度", "態度", "태도"),
    e("purpose", "noun", "B1", "Thoughts & Emotions", "der Zweck", "цель", "мета", "el propósito", "le but", "lo scopo", "o propósito", "目的", "目的", "목적"),
    e("curious", "adjective", "B1", "Thoughts & Emotions", "neugierig", "любопытный", "допитливий", "curioso", "curieux", "curioso", "curioso", "好奇的", "好奇心旺盛な", "호기심 많은"),
    e("polite", "adjective", "B1", "Society & Culture", "höflich", "вежливый", "ввічливий", "educado", "poli", "educato", "educado", "礼貌的", "丁寧な", "공손한"),
    e("fair", "adjective", "B1", "Society & Culture", "fair", "справедливый", "справедливий", "justo", "juste", "giusto", "justo", "公平的", "公平な", "공정한"),
    e("active", "adjective", "B1", "Everyday Life", "aktiv", "активный", "активний", "activo", "actif", "attivo", "ativo", "积极的", "積極的な", "활동적인"),
    e("brave", "adjective", "B1", "Thoughts & Emotions", "tapfer", "храбрый", "хоробрий", "valiente", "courageux", "coraggioso", "corajoso", "勇敢的", "勇敢な", "용감한"),
    e("serious", "adjective", "B1", "Thoughts & Emotions", "ernst", "серьёзный", "серйозний", "serio", "sérieux", "serio", "sério", "严肃的", "真面目な", "심각한"),
    e("positive", "adjective", "B1", "Thoughts & Emotions", "positiv", "позитивный", "позитивний", "positivo", "positif", "positivo", "positivo", "积极的", "前向きな", "긍정적인"),
    e("negative", "adjective", "B1", "Thoughts & Emotions", "negativ", "негативный", "негативний", "negativo", "négatif", "negativo", "negativo", "消极的", "否定的な", "부정적인"),
    e("suitable", "adjective", "B1", "Descriptions & Quality", "geeignet", "подходящий", "підходящий", "adecuado", "approprié", "adatto", "adequado", "合适的", "適切な", "적합한"),
    e("rarely", "adverb", "B1", "Everyday Life", "selten", "редко", "рідко", "raramente", "rarement", "raramente", "raramente", "很少", "滅多に", "드물게"),
    e("perfectly", "adverb", "B1", "Descriptions & Quality", "perfekt", "идеально", "ідеально", "perfectamente", "parfaitement", "perfettamente", "perfeitamente", "完美地", "完璧に", "완벽하게"),
    e("recently", "adverb", "B1", "Everyday Life", "kürzlich", "недавно", "нещодавно", "recientemente", "récemment", "recentemente", "recentemente", "最近", "最近", "최근에"),
    e("naturally", "adverb", "B1", "Everyday Life", "natürlich", "естественно", "природно", "naturalmente", "naturellement", "naturalmente", "naturalmente", "自然地", "当然", "자연스럽게"),

    # B2/C1 Concepts
    e("structure", "noun", "B2", "Professional & Tech", "die Struktur", "структура", "структура", "la estructura", "la structure", "la struttura", "a estrutura", "结构", "構造", "구조"),
    e("debate", "noun", "B2", "Society & Culture", "die Debatte", "дебаты", "дебати", "el debate", "le débat", "il dibattito", "o debate", "辩论", "討論", "토론"),
    e("analysis", "noun", "B2", "Professional & Tech", "die Analyse", "анализ", "аналіз", "el análisis", "l'analyse", "l'analisi", "a análise", "分析", "分析", "분석"),
    e("competence", "noun", "B2", "Professional & Tech", "die Kompetenz", "компетентность", "компетентність", "la competencia", "la compétence", "la competenza", "a competência", "能力", "能力", "역량"),
    e("criteria", "noun", "B2", "Professional & Tech", "das Kriterium", "критерий", "критерій", "el criterio", "le critère", "il criterio", "o critério", "标准", "基準", "기준"),
    e("argument", "noun", "B2", "Thoughts & Emotions", "das Argument", "аргумент", "аргумент", "el argumento", "l'argument", "l'argomento", "o argumento", "论据", "論点", "논거"),
    e("hypothesis", "noun", "B2", "Professional & Tech", "die Hypothese", "гипотеза", "гіпотеза", "la hipótesis", "l'hypothèse", "l'ipotesi", "a hipótese", "假设", "仮説", "가설"),
    e("priority", "noun", "B2", "Professional & Tech", "die Priorität", "приоритет", "пріоритет", "la prioridad", "la priorité", "la priorità", "a prioridade", "优先事项", "優先順位", "우선순위"),
    e("principle", "noun", "B2", "Thoughts & Emotions", "das Prinzip", "принцип", "принцип", "el principio", "le principe", "il principio", "o princípio", "原则", "原則", "원칙"),
    e("initiative", "noun", "B2", "Society & Culture", "die Initiative", "инициатива", "ініціатива", "la iniciativa", "l'initiative", "l'iniziativa", "a iniciativa", "倡议", "主導権", "주도권"),
    e("perception", "noun", "B2", "Thoughts & Emotions", "die Wahrnehmung", "восприятие", "сприйняття", "la percepción", "la perception", "la percezione", "a percepção", "知觉", "知覚", "인식"),
    e("tension", "noun", "B2", "Society & Culture", "die Spannung", "напряжение", "напруження", "la tensión", "la tension", "la tensione", "a tensão", "紧张", "緊張", "긴장"),
    e("aspect", "noun", "B2", "Thoughts & Emotions", "der Aspekt", "аспект", "аспект", "el aspecto", "l'aspect", "l'aspetto", "o aspecto", "方面", "側面", "측면"),
    e("correlation", "noun", "B2", "Professional & Tech", "der Zusammenhang", "взаимосвязь", "взаємозв'язок", "la correlación", "la corrélation", "la correlazione", "a correlação", "相关性", "相関関係", "상관관계"),
    e("interaction", "noun", "B2", "Society & Culture", "die Interaktion", "взаимодействие", "взаємодія", "la interacción", "l'interaction", "l'interazione", "a interação", "互动", "相互作用", "상호작용"),
    e("obligation", "noun", "B2", "Society & Culture", "die Verpflichtung", "обязательство", "зобов'язання", "la obligación", "l'obligation", "l'obbligo", "a obrigação", "义务", "義務", "의무"),
    e("dynamic", "noun", "B2", "Professional & Tech", "die Dynamik", "динамика", "динаміка", "la dinámica", "la dynamique", "la dinamica", "a dinâmica", "动态", "ダイナミクス", "역학"),
    e("transition", "noun", "B2", "Professional & Tech", "der Übergang", "переход", "перехід", "la transición", "la transition", "la transizione", "a transição", "过渡", "移行", "과도기"),
    e("complexity", "noun", "B2", "Professional & Tech", "die Komplexität", "сложность", "складність", "la complejidad", "la complexité", "la complessità", "a complexidade", "复杂性", "複雑さ", "복잡성"),
    e("scope", "noun", "B2", "Professional & Tech", "der Umfang", "масштаб", "обсяг", "el alcance", "la portée", "l'ambito", "o escopo", "范围", "範囲", "범위"),
    e("framework", "noun", "B2", "Professional & Tech", "der Rahmen", "структура", "рамки", "el marco", "le cadre", "il quadro", "o quadro", "框架", "枠組み", "체계"),
    e("impact", "noun", "B2", "Thoughts & Emotions", "die Auswirkung", "влияние", "вплив", "el impacto", "l'impact", "l'impatto", "o impacto", "影响", "影響", "영향"),
    e("diversity", "noun", "B2", "Society & Culture", "die Vielfalt", "разнообразие", "різноманітність", "la diversidad", "la diversité", "la diversità", "a diversidade", "多样性", "多様性", "다양성"),
    e("equilibrium", "noun", "B2", "Nature & Environment", "das Gleichgewicht", "равновесие", "рівновага", "el equilibrio", "l'équilibre", "l'equilibrio", "o equilíbrio", "平衡", "均衡", "균형"),
    e("consensus", "noun", "B2", "Society & Culture", "die Einigkeit", "согласие", "згода", "el consenso", "le consensus", "il consenso", "o consenso", "一致意见", "一致", "일치"),
    e("infrastructure", "noun", "B2", "Professional & Tech", "die Infrastruktur", "инфраструктура", "інфраструктура", "la infraestructura", "l'infrastructure", "l'infrastruttura", "a infraestrutura", "基础设施", "社会基盤", "기반 시설"),
    e("credibility", "noun", "B2", "Thoughts & Emotions", "die Glaubwürdigkeit", "достоверность", "достовірність", "la credibilidad", "la crédibilité", "la credibilità", "a credibilidade", "公信力", "信頼性", "신뢰도"),
    e("thorough", "adjective", "B2", "Descriptions & Quality", "gründlich", "тщательный", "ретельний", "minucioso", "minutieux", "minuzioso", "minucioso", "透彻的", "徹底的な", "철저한"),
    e("distinct", "adjective", "B2", "Descriptions & Quality", "ausgeprägt", "отчетливый", "виразний", "distinto", "distinct", "distinto", "distinto", "明显的", "明確な", "뚜렷한"),
    e("transparent", "adjective", "B2", "Society & Culture", "transparent", "прозрачный", "прозорий", "transparente", "transparent", "trasparente", "transparente", "透明的", "透明な", "투명한"),
    e("remarkable", "adjective", "B2", "Descriptions & Quality", "bemerkenswert", "замечательный", "чудовий", "notable", "remarquable", "notevole", "notável", "引人注目的", "注目すべき", "주목할 만한"),
    e("consistent", "adjective", "B2", "Descriptions & Quality", "beständig", "последовательный", "послідовний", "coherente", "cohérent", "coerente", "coerente", "始终如一的", "一貫した", "일관된"),
    e("objective", "adjective", "B2", "Thoughts & Emotions", "objektiv", "объективный", "об'єктивний", "objetivo", "objectif", "obiettivo", "objetivo", "客观的", "客観的な", "객관적인"),
    e("subjective", "adjective", "B2", "Thoughts & Emotions", "subjektiv", "субъективный", "суб'єктивний", "subjetivo", "subjectif", "soggettivo", "subjetivo", "主观的", "主観的な", "주관적인"),
    e("crucial", "adjective", "B2", "Descriptions & Quality", "entscheidend", "решающий", "вирішальний", "crucial", "crucial", "cruciale", "crucial", "至关重要的", "決定的な", "결정적인"),
    e("substantial", "adjective", "B2", "Descriptions & Quality", "erheblich", "существенный", "істотний", "sustancial", "substantiel", "sostanziale", "substancial", "实质性的", "実質的な", "상당한"),
    e("rigorous", "adjective", "B2", "Professional & Tech", "streng", "строгий", "суворий", "riguroso", "rigoureux", "rigoroso", "rigoroso", "严密的", "厳格な", "엄격한"),
    e("versatile", "adjective", "B2", "Descriptions & Quality", "vielseitig", "универсальный", "універсальний", "versátil", "polyvalent", "versatile", "versátil", "多才多艺的", "多才な", "다재다능한"),
    e("intricate", "adjective", "B2", "Descriptions & Quality", "verschlungen", "запутанный", "заплутаний", "intrincado", "complexe", "intricato", "intrincado", "错综复杂的", "入り組んだ", "복잡한"),
    e("precisely", "adverb", "B2", "Descriptions & Quality", "genau", "точно", "точно", "precisamente", "précisément", "precisamente", "precisamente", "精确地", "正確に", "정확히")
]

print("Expansion Words count:", len(EXPANSION_WORDS))
